name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for opening an issue to minima🦄. The issue will soon be reviewed 🔨'
        pr-message: 'Thank you for showing interest in minima🦄 and contributing to it. The Pr would soon be reviewed by the maintainer'
